spring:
  application:
    name: heifan-code-test
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  port: 0
  servlet:
    context-path: /heifan/test

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.heifan.code.test.domain.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl